
pipeline {
    agent any

    environment {
		APP = 'unknown'
    }

    stages {
        stage('Preparation') {
			steps {
				echo "Hello from Nexus-IQ pipeline"
				echo "${IQ_ORGANISATION}"
				echo "${IQ_APPLICATION}"
			}
		}
		
		stage('Create Nexus IQ Organisation'){
			steps {
				echo 'Create Nexus IQ Organisation'
				// try {
                //         //def response = sh returnStdout: true, script: 'curl -u admin:admin123 -X POST -H "Content-Type: application/json" -d '{"name": "My Organization"}' http://localhost:8070/api/v2/organizations'
                //         def response = sh returnStdout: true, script: "curl -u admin:admin123 -X POST -H 'Content-Type: application/json' -d '{\"name\": \"${IQ_ORGANISATION}\"}' http://localhost:8070/api/v2/organizations"
				// 		echo "${response}"
                // }
                // catch (error) {
                //     throw error
                // }
			}
		}

		// stage('Create Nexus IQ Application'){
		// 	steps {
		// 		try {
        //                 def response = sh returnStdout: true, script: 'curl -u admin:admin123 -X GET http://localhost:8070/api/v2/applications?publicId=Autoapps_Build-Auto-pp'
        //                 echo "${response}"
        //             }
        //             catch (error) {
        //                 throw error
        //             }
		// 	}
		// }
	}
}


